name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.12.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_auth

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  collection: ^1.18.0
  fhir: ^0.12.0
  # fhir:
  #   path: ../fhir
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_web_auth_2: ^3.1.1
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  http_parser: ^4.0.2
  jwt_decoder: ^2.0.1
  oauth2: ^2.0.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  import_sorter: ^4.6.0
  test: ^1.25.2
